### ISSUE TITLE
Infrastructure: Add appsettings/secrets in cd pipeline for app deployment

### ISSUE THREAD

**Issue by yahya130** [buerokratt/Infrastructure#41]
At the moment the appsettings/secrets are missing for each deployed app on k8s, this is likely to cause apps (dmr currently) to crash or not function properly. The best way to do this would be through the helm charts e.g.

![Image](https://user-images.githubusercontent.com/15343044/174981957-4a9404a9-49d4-4145-b01d-f7baf0a4a4c5.png)

- [x] Add app settings/sercrets to dmr
- [x] Add app settings/sercrets to mock bot
- [x] Add app settings/sercrets to mock classifier

**Comment by martinkearn** [comment]
@yahya130  ..... please link the PR for this so we can review it.

Also, you have not "ticked" the acceptance criteria?

Thanks
