### ISSUE TITLE
Infrastructure: Helm charts for Mock Classifier

### ISSUE THREAD

**Issue by decodingahmed** [buerokratt/Infrastructure#5]
As a DevOps engineer
I want to have a helm chart for the Mock Classifier application
So that I can deploy the Mock Classifier to an already provisioned AKS cluster

**Out of scope:** provision of any cloud resources

### Acceptance Criteria
- [x] Created a folder structure for helm charts for all applications in the Infrastructure repo
- [x] Created a helm chart for the Mock Classifier in the pre-agreed structure
- [x] Ensured that the helm chart deploys the application to the AKS cluster manually
- [x] Ensured that the values.yaml contains correct application configuration

**Comment by martinkearn** [comment]
@yahya130 @decodingahmed Where is the PR for this issue? It is not linked by the look of it. Thanks

**Comment by martinkearn** [comment]
Ignore. Added in error

**Comment by decodingahmed** [comment]
All acceptance criteria met
