### ISSUE TITLE
Infrastructure: Add Cosmos backup

### ISSUE THREAD

**Issue by decodingahmed** [buerokratt/Infrastructure#65]
AS AN Architect
I WANT the data in Cosmos to be recoverable in the case where the Cosmos service gets deleted and recreated with an empty database
SO THAT I do not have to manually re-register all the system participants

Configure Cosmos to use the built-in backup functionality

## Acceptance Criteria

- [x] Update Terraform to provision Cosmos with backup enabled https://github.com/buerokratt/Infrastructure/pull/72
- [x] Register some participants and manually test that data can be restored if Cosmos is re-provisioned 
- [x] Add documentation to sign-post on how to perform a data restore

**Comment by martinkearn** [comment]
Terraform module for Cosmos backup
https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/cosmosdb_account#backup

Suggested values 

```
resource "azurerm_cosmosdb_account" "db" {

  backup {
    type = "Periodic",
    interval_in_minutes = 1440
    retention_in_hours = 192
    storage_redundancy = "Geo"
  }
```
