### ISSUE TITLE
Infrastructure: Replicate Helm and CI/CD on to Azure

### ISSUE THREAD

**Issue by shelabd** [buerokratt/Infrastructure#8]
Once the helm charts for the Mock Classifier are created and the deployments to AKS are underway, we need to replicate these (helm charts and deployment pipeline) for the DMR and MBot

Depends on: #5 

### Acceptance Criteria

- [x] Helm chart for MBot created and deployed to AKS
- [x] Helm chart for DMR created and deployed to AKS
- [x] Pipeline for executing Helm CLI to apply charts to AKS - MBot
- [x] Pipeline for executing Helm CLI to apply charts to AKS - DMR

**Comment by martinkearn** [comment]
@decodingahmed, it feels like this is a duplicated task and we have this covered elsewhere in tasks for each repo, is that right?

**Comment by decodingahmed** [comment]
I've added more details, so this is ready to groom.

**Comment by martinkearn** [comment]
@decodingahmed presumably, this is needed for MS1, is that correct?

**Comment by decodingahmed** [comment]
@martinkearn yes this is indeed required for MS1. This ticket will allow us to deploy all applications to AKS.
